### ISSUE TITLE
object `function_calls` in `level_three()` is not properly initialised

### ISSUE THREAD

**Issue by huizezhang-sherry** [etiennebacher/fasttyper#1]
``` r
library(fasttyper)
level_three()
#> Error in system.time({: object 'function_calls' not found
#> Timing stopped at: 0.001 0 0
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by etiennebacher** [comment]
This should be solved now (b40e6451501a80638573c7e9ec428b04192a89c7), you must reinstall the github version. Thanks for reporting this, and feel free to reopen if it doesn't work.
